POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "id": "1",
  "name": "катя",
  "email": "катя@гугл.ком",
  "password": "суперпароль"
}


###
POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "id": "2",
  "name": "вася",
  "email": "вася@гугл.ком",
  "password": "суперпуперпароль"
}

###
POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "id": "3",
  "name": "михаил иванович",
  "email": "михаил1955@гугл.ком",
  "password": "19551212"
}


###
GET http://127.0.0.1:8080/user
Accept: application/json

###
GET http://127.0.0.1:8080/user/1
Accept: application/json

###
GET http://127.0.0.1:8080/user/4
Accept: application/json

###
DELETE http://127.0.0.1:8080/user/2

###
DELETE http://127.0.0.1:8080/user/5


###
POST http://127.0.0.1:8080/user/login
Content-Type: application/json

{
  "id": "1",
  "name": "катя",
  "email": "катя@гугл.ком",
  "password": "суперпароль"
}


###
GET http://127.0.0.1:8080/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJuYW1lIjoi0LrQsNGC0Y8iLCJleHAiOjE2OTgzMjM5MDB9.WJfM3cKY_wDCW9ZEb9fhejtSDoyTpqNeZWD7efByI70


###
POST http://127.0.0.1:8080/user/1/portfolios
Content-Type: application/json

{
  "id": "5",
  "user_id": "1",
  "name": "first"
}


###
POST http://127.0.0.1:8080/user/1/portfolios
Content-Type: application/json

{
  "id": "1",
  "user_id": "1",
  "name": "second"
}


###
GET http://127.0.0.1:8080/user/1/portfolios
Accept: application/json


###
GET http://127.0.0.1:8080/user/2/portfolios
Accept: application/json




