
###
POST http://127.0.0.1:8080/stock
Content-Type: application/json

{
  "id_portfolio" : "26",
  "id_company" : "8",
  "amount": 5,
  "name" : "asdasfsdf",
  "current_price": 110.0,
  "purchase_price": 90.0
}

###
POST http://127.0.0.1:8080/stock
Content-Type: application/json

{
  "id_portfolio" : "30",
  "id_company" : "8",
  "amount": 2,
  "name" : "a89554uiwejfkdm",
  "current_price": 0.0,
  "purchase_price": 90.0
}

###
GET http://127.0.0.1:8080/stock/portfolio/26
Accept: application/json

###
GET http://127.0.0.1:8080/stock/portfolio/1
Accept: application/json

###
GET http://127.0.0.1:8080/stock/5
Accept: application/json

###
GET http://127.0.0.1:8080/stock/22
Accept: application/json

###
DELETE http://127.0.0.1:8080/stock/26