POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "name": "юзер1",
  "email": "юююююю@гугл.ком",
  "password": "зеер"
}


###
POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "name": "юзер11",
  "email": "апчих@гугл.ком",
  "password": "кхекхе"
}

###
GET http://127.0.0.1:8080/user
Accept: application/json

###
GET http://127.0.0.1:8080/user/2
Accept: application/json

###
GET http://127.0.0.1:8080/user/33
Accept: application/json

###
DELETE http://127.0.0.1:8080/user/33

###
DELETE http://127.0.0.1:8080/user/18





