###
POST http://127.0.0.1:8080/user/2/portfolios
Content-Type: application/json

{
  "user_id": "2",
  "name": "tink",
  "price": 231.3,
  "total_profit": 2423.1,
  "profitability": 56.51,
  "change_day": 546.00
}


###
POST http://127.0.0.1:8080/user/2/portfolios
Content-Type: application/json

{
  "user_id": "2",
  "name": "tink",
  "price": 231.3,
  "total_profit": 2423.1,
  "profitability": 56.51,
  "change_day": 546.00
}


###
GET http://127.0.0.1:8080/user/1/portfolios
Accept: application/json


###
GET http://127.0.0.1:8080/user/2/portfolios
Accept: application/json


###
DELETE http://127.0.0.1:8080/user/2/portfolios/25
